sudo: required

language: generic

env:
  matrix:
    - OS_TYPE=fedora OS_VERSION=28
    - OS_TYPE=fedora OS_VERSION=27
    - OS_TYPE=fedora OS_VERSION=26
    - OS_TYPE=centos OS_VERSION=7
    - OS_TYPE=centos OS_VERSION=6

services:
  - docker

install:
  - ./crypt-keeper generate ${OS_TYPE} ${OS_VERSION}

script:
  - ./crypt-keeper build ${OS_TYPE} ${OS_VERSION}

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./crypt-keeper push ${OS_TYPE} ${OS_VERSION}

